eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://192.168.19.17:3306/TRAINING?useSSL=false&serverTimezone=UTC
    username: traininguser
    password: Tra!n$pa$$
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: PAYMENT_SERVICE

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
